#!/bin/sh
# File preview handler for lf using sixel via chafa

set -C -f
IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}"

# Preview image using chafa+sixel
image() {
    if command -v chafa >/dev/null 2>&1; then
        chafa -f sixel -s "$2x$3" --animate off --polite on "$1"
    else
        echo "chafa not found" >&2
    fi
}

CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/lf"

case "$(file --dereference --brief --mime-type -- "$1")" in
    image/avif)
        CACHE="$CACHE_DIR/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1).jpg"
        [ ! -f "$CACHE" ] && magick "$1" "$CACHE"
        image "$CACHE" "$2" "$3"
        ;;
    image/vnd.djvu)
        CACHE="$CACHE_DIR/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1).jpg"
        [ ! -f "$CACHE" ] && djvused "$1" -e 'select 1; save-page-with /dev/stdout' | magick -density 200 - "$CACHE"
        image "$CACHE" "$2" "$3"
        ;;
    image/svg+xml)
        CACHE="$CACHE_DIR/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1).png"
        [ ! -f "$CACHE" ] && inkscape --export-type=png --export-filename="$CACHE" "$1"
        image "$CACHE" "$2" "$3"
        ;;
    image/x-xcf)
        CACHE="$CACHE_DIR/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1).jpg"
        [ ! -f "$CACHE" ] && magick "$1[0]" "$CACHE"
        image "$CACHE" "$2" "$3"
        ;;
    image/*)
        image "$1" "$2" "$3"
        ;;
    text/html)
        lynx -width="$2" -display_charset=utf-8 -dump "$1"
        ;;
    text/troff)
        man ./ "$1" | col -b
        ;;
    text/* | */xml | application/json | application/x-ndjson)
        bat -p --theme ansi --terminal-width "$(($2-2))" -f "$1"
        ;;
    audio/* | application/octet-stream)
        mediainfo "$1"
        ;;
    video/*)
        CACHE="$CACHE_DIR/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1).jpg"
        [ ! -f "$CACHE" ] && ffmpegthumbnailer -i "$1" -o "$CACHE" -s 0
        image "$CACHE" "$2" "$3"
        ;;
    */pdf)
        CACHE="$CACHE_DIR/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1).jpg"
        [ ! -f "$CACHE" ] && pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
        image "$CACHE.jpg" "$2" "$3"
        ;;
    */epub+zip|*/mobi*)
        CACHE="$CACHE_DIR/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1).jpg"
        [ ! -f "$CACHE" ] && gnome-epub-thumbnailer "$1" "$CACHE"
        image "$CACHE" "$2" "$3"
        ;;
    application/*zip)
        atool --list -- "$1"
        ;;
    *opendocument*)
        odt2txt "$1"
        ;;
    application/pgp-encrypted)
        gpg -d -- "$1"
        ;;
esac

exit 1
