set -a terminal-features "tmux-256color:RGB"
set -g extended-keys on
set -g base-index 1
set -g renumber-windows on
setw -g mode-keys vi
set -g mouse on
set -g escape-time 0
set -g repeat-time 250

set -g status-position top
set -g status-justify absolute-centre
set -g status-style 'bg=default'
set -g window-status-current-style "fg=black bg=white  "
set -g window-status-current-style "fg=colour255,bg=default,bold"
set -g window-status-separator ""
set -g window-status-format "#[fg=colour240]#[default] #I:#W#{?window_flags,#{window_flags},} #[fg=colour240]#[default]"
set -g window-status-current-format "#[fg=colour252]#[default] #I:#W#{?window_flags,#{window_flags},} #[fg=colour252]#[default]"
set -g status-interval 5
set -g status-left '#S'
set -g status-right ''

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux reloaded"
bind b set -g status
bind x kill-window
bind-key f run-shell "tmux neww $HOME/.local/bin/tmux-sessionizer"
bind-key b set-option status

bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

bind -r C-h resize-pane -L 5   
bind -r C-j resize-pane -D 5   
bind -r C-k resize-pane -U 5   
bind -r C-l resize-pane -R 5   

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
