hwdec=auto-safe
profile=gpu-hq
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
video-sync=display-resample

screenshot-format=png
screenshot-directory="~/Pictures/Screenshots/mpv/"
screenshot-template="%f-%wH.%wM.%wS.%wT-#%#00n"

sub-auto=fuzzy
sub-bold=yes

border=no
title-bar=no
osc=yes
loop=no
keep-open=yes
script-opts=ytdl_hook-ytdl_path=yt-dlp

cache=yes
demuxer-max-bytes=500MiB
demuxer-max-back-bytes=100MiB

